FROM openjdk:11.0.16-jdk

RUN mkdir -p /tmp/spp-probe/ca
ADD ./config/spp-platform.crt /tmp/spp-probe/ca/ca.crt

ADD ./spp-probe.yml /tmp/spp-probe
ADD ./spp-probe-*.jar /tmp/spp-probe/spp-probe.jar

ENV SPP_DELETE_PROBE_DIRECTORY_ON_BOOT=false

ADD ./Main.java /
ADD ./VariableTests.java /
ADD ./SpanTests.java /

RUN javac -g Main.java VariableTests.java SpanTests.java

CMD [ "java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5105", "-javaagent:/tmp/spp-probe/spp-probe.jar", "Main" ]